### !!!

In [2]:
!pip install transformers datasets

Requirement already satisfied: transformers in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (4.47.0)
Requirement already satisfied: datasets in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (3.2.0)
Requirement already satisfied: filelock in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.26.5)
Requirement already satisfied: numpy>=1.17 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (24.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from transformers) (4.66.5)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from datasets) (2.2.1)
Requirement already satisfied: xxhash in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.9.0)
Requirement already satisfied: aiohttp in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.9.5)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from requests->transformers) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from requests->transformers) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from requests->transformers) (2024.2.2)
Requirement already satisfied: colorama in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)

In [6]:
import pandas as pd

splits = {'train': 'full/train-00000-of-00001.parquet', 'test': 'full/test-00000-of-00001.parquet', 'validation': 'full/validation-00000-of-00001.parquet', 'prompt': 'full/prompt-00000-of-00001.parquet'}
mbpp_df = pd.read_parquet("hf://datasets/google-research-datasets/mbpp/" + splits["train"])

In [7]:
mbpp_df

,task_id,text,code,test_list,test_setup_code,challenge_test_list
0,601,Write a function to find the longest chain whi...,"class Pair(object): \r\n\tdef __init__(self, a...","[assert max_chain_length([Pair(5, 24), Pair(15...",,[]
1,602,Write a python function to find the first repe...,"def first_repeated_char(str1):\r\n for index,...","[assert first_repeated_char(""abcabc"") == ""a"", ...",,[]
2,603,Write a function to get a lucid number smaller...,def get_ludic(n):\r\n\tludics = []\r\n\tfor i ...,"[assert get_ludic(10) == [1, 2, 3, 5, 7], asse...",,[]
3,604,Write a function to reverse words in a given s...,def reverse_words(s):\r\n return ' '.jo...,"[assert reverse_words(""python program"")==(""pro...",,[]
4,605,Write a function to check if the given integer...,def prime_num(num):\r\n if num >=1:\r\n for...,"[assert prime_num(13)==True, assert prime_num(...",,[]
...,...,...,...,...,...,...
369,970,Write a function to find minimum of two numbers.,"def min_of_two( x, y ):\r\n if x < y:\r\n ...","[assert min_of_two(10,20)==10, assert min_of_t...",,[]
370,971,Write a function to find the maximum number of...,"def maximum_segments(n, a, b, c) : \r\n\tdp = ...","[assert maximum_segments(7, 5, 2, 5) == 2, ass...",,[]
371,972,Write a function to concatenate the given two ...,"def concatenate_nested(test_tup1, test_tup2):\...","[assert concatenate_nested((3, 4), (5, 6)) == ...",,[]
372,973,Write a python function to left rotate the str...,"def left_rotate(s,d):\r\n tmp = s[d : ] + s...","[assert left_rotate(""python"",2) == ""thonpy"" ...",,[]
373,974,Write a function to find the minimum total pat...,def min_sum_path(A): \r\n\tmemo = [None] * len...,"[assert min_sum_path([[ 2 ], [3, 9 ], [1, 6, 7...",,[]

In [2]:
import os
from dotenv import load_dotenv

In [3]:
load_dotenv()

True

### Load Dataset

In [8]:
from datasets import load_dataset

In [15]:
ds = load_dataset("codeparrot/apps")

In [16]:
ds

DatasetDict({
    train: Dataset({
        features: ['problem_id', 'question', 'solutions', 'input_output', 'difficulty', 'url', 'starter_code'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['problem_id', 'question', 'solutions', 'input_output', 'difficulty', 'url', 'starter_code'],
        num_rows: 5000
    })
})

In [17]:
train_dataset = ds["train"]
df = train_dataset.to_pandas()
df

,problem_id,question,solutions,input_output,difficulty,url,starter_code
0,0,Polycarp has $n$ different binary words. A wor...,"[""for _ in range(int(input())):\n n = int(i...","{\n ""inputs"": [\n ""4\n4\n0001\n1000\n0011\...",interview,https://codeforces.com/problemset/problem/1259/D,
1,1,Mikhail walks on a Cartesian plane. He starts ...,"[""q=int(input())\n\nfor e in range(q):\n x,...","{\n ""inputs"": [\n ""3\n2 2 3\n4 3 7\n10 1 9...",interview,https://codeforces.com/problemset/problem/1036/B,
2,2,"You are given three sequences: $a_1, a_2, \ldo...","[""import sys\nimport random\nfrom fractions im...","{\n ""inputs"": [\n ""5\n3\n1 1 1\n2 2 2\n3 3...",interview,https://codeforces.com/problemset/problem/1408/A,
3,3,"You have $n$ barrels lined up in a row, number...","[""def solve():\n n, k = map(int,input().spl...","{\n ""inputs"": [\n ""2\n4 1\n5 5 5 5\n3 2\n0...",interview,https://codeforces.com/problemset/problem/1430/B,
4,4,"You are given a permutation $p=[p_1, p_2, \ldo...","[""for _ in range(int(input())):\n input()\n...","{\n ""inputs"": [\n ""3\n6\n4 5 1 3 2 6\n5\n5...",interview,https://codeforces.com/problemset/problem/1265/B,
...,...,...,...,...,...,...,...
4995,4995,Another rewarding day in the fast-paced world ...,"[""class HTMLGen:\n def __init__(self):\n ...","{""fn_name"": ""__init__"", ""inputs"": [], ""outputs...",introductory,https://www.codewars.com/kata/54eecc187f9142cc...,\ndef __init__(self):\n\t
4996,4996,## **Instructions**\n\nThe goal of this kata i...,"[""def fibs_fizz_buzz(n):\n a, b, out = 0, 1...","{""fn_name"": ""fibs_fizz_buzz"", ""inputs"": [], ""o...",introductory,https://www.codewars.com/kata/57bf599f102a39bb...,\ndef fibs_fizz_buzz(n):\n\t
4997,4997,"The function sigma 1, σ1 in mathematics, is kn...","[""cache = {}\ndef sum_div(x):\n if x not in...","{""fn_name"": ""sigma1"", ""inputs"": [], ""outputs"":...",introductory,https://www.codewars.com/kata/5619dbc22e69620e...,\ndef sigma1(n):\n\t
4998,4998,The principal of a school likes to put challen...,"[""def wanted_words(vowels, consonants, forbidd...","{""fn_name"": ""wanted_words"", ""inputs"": [[1, 7, ...",introductory,https://www.codewars.com/kata/580be55ca671827c...,"\ndef wanted_words(n, m, forbid_let):\n\t"
4999,4999,Complete the method that takes a sequence of o...,"[""def capital(capitals):\n return [f\""The c...","{""fn_name"": ""capital"", ""inputs"": [], ""outputs""...",introductory,https://www.codewars.com/kata/53573877d5493b4d...,\ndef capital(capitals):\n\t

In [18]:
df.to_csv("train.csv", index = False)

In [19]:
from transformers import RobertaTokenizer

tokenizer = RobertaTokenizer.from_pretrained("Salesforce/codet5-base")

### Preprocess the data

In [20]:
import cohere

In [21]:
cohere_api_key = '7DNoxjgNM7h9ffV8WGcQYPnsggQUUhq2UYywfk3Z'
co = cohere.Client(cohere_api_key)

In [42]:
def preprocessing(dataframe):
    responses = []
    model_name = "command-r-plus"
    for _, row in dataframe.iterrows():
        prompt = row["question"]
        task_id = row["problem_id"]
        solution = row["solutions"]
        try:
            generated_soln = co.generate(
                model=model_name,  
                prompt=prompt,
                temperature=0.7
            )
            responses.append(
                {
                    "task_id": task_id,
                    "prompt": prompt,
                    "solution": solution,
                    "generated_output": generated_soln
                }
            )
        except Exception as e:
            print(f"Error generating response for prompt: {task_id}\n{e}")
            responses.append(
                {
                    "task_id": task_id,
                    "prompt": prompt,
                    "solution": solution,
                    "generated_output": ""
                }
            )
    return responses

In [43]:
train_responses = preprocessing(df)

KeyboardInterrupt:

In [44]:
len(train_responses)

5000

In [52]:
train_responses[0]

{'task_id': 0,
 'prompt': 'Polycarp has $n$ different binary words. A word called binary if it contains only characters \'0\' and \'1\'. For example, these words are binary: "0001", "11", "0" and "0011100".\n\nPolycarp wants to offer his set of $n$ binary words to play a game "words". In this game, players name words and each next word (starting from the second) must start with the last character of the previous word. The first word can be any. For example, these sequence of words can be named during the game: "0101", "1", "10", "00", "00001".\n\nWord reversal is the operation of reversing the order of the characters. For example, the word "0111" after the reversal becomes "1110", the word "11010" after the reversal becomes "01011".\n\nProbably, Polycarp has such a set of words that there is no way to put them in the order correspondent to the game rules. In this situation, he wants to reverse some words from his set so that:  the final set of $n$ words still contains different words (i.e. all words are unique);  there is a way to put all words of the final set of words in the order so that the final sequence of $n$ words is consistent with the game rules. \n\nPolycarp wants to reverse minimal number of words. Please, help him.\n\n\n-----Input-----\n\nThe first line of the input contains one integer $t$ ($1 \\le t \\le 10^4$) — the number of test cases in the input. Then $t$ test cases follow.\n\nThe first line of a test case contains one integer $n$ ($1 \\le n \\le 2\\cdot10^5$) — the number of words in the Polycarp\'s set. Next $n$ lines contain these words. All of $n$ words aren\'t empty and contains only characters \'0\' and \'1\'. The sum of word lengths doesn\'t exceed $4\\cdot10^6$. All words are different.\n\nGuaranteed, that the sum of $n$ for all test cases in the input doesn\'t exceed $2\\cdot10^5$. Also, guaranteed that the sum of word lengths for all test cases in the input doesn\'t exceed $4\\cdot10^6$.\n\n\n-----Output-----\n\nPrint answer for all of $t$ test cases in the order they appear.\n\nIf there is no answer for the test case, print -1. Otherwise, the first line of the output should contain $k$ ($0 \\le k \\le n$) — the minimal number of words in the set which should be reversed. The second line of the output should contain $k$ distinct integers — the indexes of the words in the set which should be reversed. Words are numerated from $1$ to $n$ in the order they appear. If $k=0$ you can skip this line (or you can print an empty line). If there are many answers you can print any of them.\n\n\n-----Example-----\nInput\n4\n4\n0001\n1000\n0011\n0111\n3\n010\n101\n0\n2\n00000\n00001\n4\n01\n001\n0001\n00001\n\nOutput\n1\n3 \n-1\n0\n\n2\n1 2',
 'solution': '["for _ in range(int(input())):\\n    n = int(input())\\n    mass = []\\n    zo = 0\\n    oz = 0\\n    zz = 0\\n    oo = 0\\n    ozs = []\\n    zos = []\\n    ozss = set()\\n    zoss = set()\\n    for j in range(n):\\n        k = input()\\n        mass.append(k)\\n        if k[0] == \'0\' and k[-1] == \'1\':\\n            zoss.add(k)\\n            zos.append(j + 1)\\n            zo += 1\\n        elif k[0] == \'1\' and k[-1] == \'0\':\\n            ozss.add(k)\\n            ozs.append(j + 1)\\n            oz += 1\\n        elif k[0] == \'0\' and k[-1] == \'0\':\\n            zz += 1\\n        else:\\n            oo += 1\\n    if zz and oo and not oz and not zo:\\n        print(-1)\\n        continue\\n    else:\\n        if zo > oz:\\n            print((zo - oz) // 2)\\n            ans = []\\n            need = (zo - oz) // 2\\n            i = 0\\n            while need:\\n                zzz = mass[zos[i] - 1][len(mass[zos[i] - 1]) - 1:: -1]\\n                if zzz not in ozss:\\n                    ans.append(zos[i])\\n                    need -= 1\\n                i += 1\\n            print(*ans)\\n        else:\\n            print((oz - zo) // 2)\\n            ans = []\\n            need = (oz - zo) // 2\\n            i = 0\\n            while need:\\n                zzz = mass[ozs[i] - 1][len(mass[ozs[i] - 1]) - 1:: -1]\\n                if zzz not in zoss:\\n                    ans.append(ozs[i])\\n                    need -= 1\\n                i += 1\\n            print(*ans)\\n", "k = int(input())\\nfor i in range(k):\\n    is_t = set()\\n    a = dict()\\n    a[\'00\'] = []\\n    a[\'11\'] = []\\n    a[\'01\'] = []\\n    a[\'10\'] = []    \\n    n = int(input())\\n    s = []\\n    for i in range(n):\\n        b = input()\\n        a[b[0] + b[-1]].append(i)\\n        s.append(b)\\n        is_t.add(b)\\n    c = len(a[\'10\'])\\n    d = len(a[\'01\'])\\n    if c + d == 0:\\n        if len(a[\'00\']) == 0 or len(a[\'11\']) == 0:\\n            print(0)\\n        else:\\n            print(-1)\\n    elif c > d:\\n        ans = []\\n        i = 0\\n        m = (d + c) // 2\\n        while d != m and i < len(a[\'10\']):\\n            s1 = s[a[\'10\'][i]]\\n            if s1[::-1] not in is_t:\\n                d += 1\\n                ans.append(a[\'10\'][i] + 1)\\n            i += 1\\n        if d != m:\\n            print(-1)\\n        else:\\n            print(len(ans))\\n            print(*ans)\\n    else:\\n        ans = []\\n        i = 0\\n        m = (d + c) // 2\\n        while c != m and i < len(a[\'01\']):\\n            s1 = s[a[\'01\'][i]]\\n            if s1[::-1] not in is_t:\\n                c += 1\\n                ans.append(a[\'01\'][i] + 1)\\n            i += 1\\n        if c != m:\\n            print(-1)\\n        else:\\n            print(len(ans))\\n            print(*ans)\\n", "N = int(input())\\n\\ndef ceildiv(x, y):\\n    if x % y == 0:\\n        return x // y\\n    else:\\n        return x // y + 1\\n\\nfor _ in range(N):\\n    doms = []\\n    oc, zc = 0, 0\\n    n = int(input())\\n\\n    used = set()\\n    fulls = dict()\\n\\n    for i in range(n):\\n        d = input()\\n        used.add(d)\\n        if d[0] != d[-1]:\\n            fulls[i] = d\\n            doms.append((i, (d[0], d[-1])))\\n        else:\\n            if d[0] == \'0\':\\n                zc = 1\\n            else:\\n                oc = 1\\n\\n    if len(doms) == 0:\\n        if zc == 1 and oc == 1:\\n            print(-1)\\n        else:\\n            print(0)\\n    else:\\n        # print(doms)\\n\\n        _01 = 0\\n        _10 = 0\\n\\n        _01_indexes = []\\n        _10_indexes = []\\n\\n\\n        for dom in doms:\\n            if dom[1] == (\'0\', \'1\'):\\n                _01 += 1\\n                _01_indexes.append(dom[0])\\n            else:\\n                _10 += 1\\n                _10_indexes.append(dom[0])\\n\\n        if _10 < _01:\\n            _01, _10 = _10, _01\\n            _01_indexes, _10_indexes = _10_indexes, _01_indexes\\n\\n        _10_indexes = [x for x in _10_indexes if fulls[x][::-1] not in used] \\n\\n        need = ceildiv(_10-_01-1, 2)\\n        if len(_10_indexes) >= need:\\n            print(need)\\n            print( \' \'.join(list([str(x+1) for x in _10_indexes[:need]])) )\\n        else:\\n            print(-1)\\n\\n    # print(\\"===\\")\\n        # print(ceil(abs(doms.count((\'0\', \'1\')) - doms.count((\'1\', \'0\'))) - 1, 2))\\n\\n", "t=int(input())\\nfor _ in range(t):\\n    n=int(input())\\n    k={\\"01\\":0,\\"00\\":0,\\"11\\":0,\\"10\\":0}\\n    ab=[]\\n    ba=[]\\n    a=[]\\n    ra=set()\\n    rb=set()\\n    for i in range(n):\\n        s=input()\\n        ts=s[0]+s[-1]\\n        k[ts]+=1\\n        if ts==\\"01\\":\\n            ab.append([str(i+1),s])\\n            ra.add(s)\\n        if ts==\\"10\\":\\n            ba.append([str(i+1),s])\\n            rb.add(s)\\n    if k[\\"01\\"]==0 and k[\\"10\\"]==0 and k[\\"00\\"]>0 and k[\\"11\\"]>0:\\n        ans=-1\\n    else:\\n        if k[\\"01\\"]==k[\\"10\\"] or k[\\"01\\"]==k[\\"10\\"]+1 or k[\\"01\\"]==k[\\"10\\"]-1:\\n            ans=0\\n        else:\\n            m=(k[\\"01\\"]+k[\\"10\\"])//2 if (k[\\"01\\"]+k[\\"10\\"])%2==0 else (k[\\"01\\"]+k[\\"10\\"])//2+1\\n            if k[\\"01\\"]>m:\\n                ans=k[\\"01\\"]-m\\n                for i in range(len(ab)):\\n                    psp=ab[i][1]\\n                    nn=list(psp)\\n                    nn.reverse()\\n                    psp=\\"\\".join(nn)\\n                    c1=len(rb)\\n                    rb.add(psp)\\n                    c2=len(rb)\\n                    if c1!=c2:\\n                        a.append(ab[i][0])\\n                if len(a)>=ans:\\n                    a=a[:ans]\\n                else:\\n                    ans=-1\\n            else:\\n                ans=k[\\"10\\"]-m\\n                for i in range(len(ba)):\\n                    psp=ba[i][1]\\n                    nn=list(psp)\\n                    nn.reverse()\\n                    psp=\\"\\".join(nn)\\n                    c1=len(ra)\\n                    ra.add(psp)\\n                    c2=len(ra)\\n                    if c1!=c2:\\n                        a.append(ba[i][0])\\n                if len(a)>=ans:\\n                    a=a[:ans]\\n                else:\\n                    ans=-1\\n    print(ans)\\n    if ans>0:\\n        print(\\" \\".join(a))\\n", "t=int(input())\\nfor i in range(t):\\n    n=int(input())\\n    i0,i1=[],[]\\n    l0,l1=[],[]\\n    h0,h1=False,False\\n    for i in range(n):\\n        t=input()\\n        if t[0]==\'0\' and t[-1]==\'1\':\\n            i0.append(i)\\n            l0.append(t)\\n        elif t[0]==\'1\' and t[-1]==\'0\':\\n            i1.append(i)\\n            l1.append(t)\\n        elif t[0]==t[-1]==\'1\':\\n            h1=True\\n        elif t[0]==t[-1]==\'0\':\\n            h0=True\\n    c0,c1=len(l0),len(l1)\\n    req,sl=0,[]\\n    s0=set(l0)\\n    s1=set(l1)\\n    if c0>0 or c1>0:\\n        if c0-c1>1:\\n            req=(c0-c1)//2\\n            sel=0\\n            sl=[]\\n            for tt in range(len(l0)):\\n                t=l0[tt]\\n                if not t[::-1] in s1:\\n                    req-=1\\n                    sl.append(i0[tt]+1)\\n                if req==0:\\n                    break\\n        elif c1-c0>1:\\n            req=(c1-c0)//2\\n            sel=0\\n            sl=[]\\n            for tt in range(len(l1)):\\n                t=l1[tt]\\n                if not t[::-1] in s0:\\n                    req-=1\\n                    sl.append(i1[tt]+1)\\n                if req==0:\\n                    break\\n        if req>0:\\n            print(-1)\\n        else:\\n            print(len(sl))\\n            print(*sl)\\n    else:\\n        if h0 and h1:\\n            print(-1)\\n        else:\\n            print(0)\\n            print(*[])\\n"]',
 'generated_output': ''}

### Gemini API

In [53]:
api_key = os.get(

In [55]:
!pip install google-generativeai

Collecting google-generativeai
  Downloading google_generativeai-0.8.3-py3-none-any.whl.metadata (3.9 kB)
Collecting google-ai-generativelanguage==0.6.10 (from google-generativeai)
  Downloading google_ai_generativelanguage-0.6.10-py3-none-any.whl.metadata (5.6 kB)
Collecting google-api-core (from google-generativeai)
  Downloading google_api_core-2.24.0-py3-none-any.whl.metadata (3.0 kB)
Collecting google-api-python-client (from google-generativeai)
  Downloading google_api_python_client-2.156.0-py2.py3-none-any.whl.metadata (6.7 kB)
Collecting google-auth>=2.15.0 (from google-generativeai)
  Downloading google_auth-2.37.0-py2.py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: protobuf in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (4.25.3)
Requirement already satisfied: pydantic in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (2.9.2)
Requirement already satisfied: tqdm in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (4.66.5)
Requirement already satisfied: typing-extensions in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (4.11.0)
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.10->google-generativeai)
  Downloading proto_plus-1.25.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from google-api-core->google-generativeai) (1.65.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from google-api-core->google-generativeai) (2.32.3)
Collecting cachetools<6.0,>=2.0.0 (from google-auth>=2.15.0->google-generativeai)
  Downloading cachetools-5.5.0-py3-none-any.whl.metadata (5.3 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth>=2.15.0->google-generativeai)
  Downloading pyasn1_modules-0.4.1-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth>=2.15.0->google-generativeai)
  Downloading rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Collecting httplib2<1.dev0,>=0.19.0 (from google-api-python-client->google-generativeai)
  Downloading httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client->google-generativeai)
  Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client->google-generativeai)
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from pydantic->google-generativeai) (2.23.4)
Requirement already satisfied: colorama in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from tqdm->google-generativeai) (0.4.6)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.10->google-generativeai) (1.64.1)
Collecting grpcio-status<2.0.dev0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.10->google-generativeai)
  Downloading grpcio_status-1.68.1-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->google-generativeai) (3.1.2)
Collecting pyasn1<0.7.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai)
  Downloading pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sulav\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2024.2.2)
Collecting protobuf (from google-generativeai)
  Downloading protobuf-5.29.2-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting grpcio<2.0dev,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.10->google-generativeai)
  Downloading grpcio-1.68.1-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
Downloading google_generativeai-0.8.3-py3-none-any.whl (160 kB)
Downloading google_ai_generativelanguage-0.6.10-py3-none-any.whl (760 kB)
   ---------------------------------------- 0.0/760.0 kB ? eta -:--:--
   ------------- -------------------------- 262.1/760.0 kB ? eta -:--:--
   ---------------------------------------- 760.0/760.0 kB 3.6 MB/s eta 0:00:00
Downloading google_api_core-2.24.0-py3-none-any.whl (158 kB)
Downloading google_auth-2.37.0-py2.py3-none-any.whl (209 kB)
Downloading google_api_python_client-2.156.0-py2.py3-none-any.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.7 MB 2.1 MB/s eta 0:00:06
   ---- ----------------------------------- 1.6/12.7 MB 2.2 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.7 MB 2.3 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.7 MB 2.4 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.7 MB 2.6 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.7 MB 2.7 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.7 MB 2.9 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.7 MB 3.0 MB/s eta 0:00:03
   -------------------- ------------------- 6.6/12.7 MB 3.1 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.7 MB 3.2 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.7 MB 3.3 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.7 MB 3.4 MB/s eta 0:00:02
   ------------------------------- -------- 10.0/12.7 MB 3.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.7 MB 3.4 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 3.6 MB/s eta 0:00:00
Downloading cachetools-5.5.0-py3-none-any.whl (9.5 kB)
Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl (9.3 kB)
Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
Downloading proto_plus-1.25.0-py3-none-any.whl (50 kB)
Downloading pyasn1_modules-0.4.1-py3-none-any.whl (181 kB)
Downloading rsa-4.9-py3-none-any.whl (34 kB)
Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Downloading grpcio_status-1.68.1-py3-none-any.whl (14 kB)
Downloading protobuf-5.29.2-cp310-abi3-win_amd64.whl (434 kB)
Downloading grpcio-1.68.1-cp312-cp312-win_amd64.whl (4.4 MB)
   ---------------------------------------- 0.0/4.4 MB ? eta -:--:--
   --------- ------------------------------ 1.0/4.4 MB 5.0 MB/s eta 0:00:01
   ------------------- -------------------- 2.1/4.4 MB 5.3 MB/s eta 0:00:01
   ---------------------------- ----------- 3.1/4.4 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 4.4/4.4 MB 5.6 MB/s eta 0:00:00
Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
Installing collected packages: uritemplate, pyasn1, protobuf, httplib2, grpcio, cachetools, rsa, pyasn1-modules, proto-plus, grpcio-status, google-auth, google-auth-httplib2, google-api-core, google-api-python-client, google-ai-generativelanguage, google-generativeai
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.3
    Uninstalling protobuf-4.25.3:
      Successfully uninstalled protobuf-4.25.3
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.64.1
    Uninstalling grpcio-1.64.1:
      Successfully uninstalled grpcio-1.64.1
Successfully installed cachetools-5.5.0 google-ai-generativelanguage-0.6.10 google-api-core-2.24.0 google-api-python-client-2.156.0 google-auth-2.37.0 google-auth-httplib2-0.2.0 google-generativeai-0.8.3 grpcio-1.68.1 grpcio-status-1.68.1 httplib2-0.22.0 proto-plus-1.25.0 protobuf-5.29.2 pyasn1-0.6.1 pyasn1-modules-0.4.1 rsa-4.9 uritemplate-4.1.1

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Sulav\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\~upb'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.17.0 requires keras>=3.2.0, but you have keras 3.0.1 which is incompatible.
tensorflow-intel 2.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 5.29.2 which is incompatible.
tensorflow-metadata 1.15.0 requires protobuf<5,>=4.25.2; python_version >= "3.11", but you have protobuf 5.29.2 which is incompatible.

In [62]:
import google.generativeai as genai
import os

genai.configure(api_key="AIzaSyCR9KSalZo60AOd93oPmJ9IHduoFpx4b1I")

model = genai.GenerativeModel('gemini-1.5-flash')
response = model.generate_content("The opposite of hot is")
print(response.text)

cold

In [96]:
def preprocessing(dataframe):
    responses = []
    model_name = "gemini-1.5-flash"
    for _, row in dataframe.iterrows():
        prompt = row["question"]
        task_id = row["problem_id"]
        solution = row["solutions"]
        try:
            generated_soln = model.generate_content(prompt)
            responses.append(
                {
                    "task_id": task_id,
                    "prompt": prompt,
                    "solution": solution,
                    "generated_output": generated_soln.text
                }
            )
            print(f"{task_id} done")
        except Exception as e:
            print(f"Error generating response for prompt: {task_id}\n{e}")
            responses.append(
                {
                    "task_id": task_id,
                    "prompt": prompt,
                    "solution": solution,
                    "generated_output": ""
                }
            )
    return responses

In [93]:
responses = []
import numpy as np
import pandas as pd

def split_dataframe(dataframe, batch_size):
    """
    Splits a DataFrame into smaller DataFrames of the specified batch size.

    Args:
        dataframe (pd.DataFrame): The DataFrame to split.
        batch_size (int): The number of rows per batch.

    Returns:
        List[pd.DataFrame]: A list of DataFrame batches.
    """
    num_batches = int(np.ceil(len(dataframe) / batch_size))
    return [dataframe.iloc[i * batch_size: (i + 1) * batch_size] for i in range(num_batches)]

batch_size = 10
batches = split_dataframe(df, batch_size)

In [94]:
batches[0]

,problem_id,question,solutions,input_output,difficulty,url,starter_code
0,0,Polycarp has $n$ different binary words. A wor...,"[""for _ in range(int(input())):\n n = int(i...","{\n ""inputs"": [\n ""4\n4\n0001\n1000\n0011\...",interview,https://codeforces.com/problemset/problem/1259/D,
1,1,Mikhail walks on a Cartesian plane. He starts ...,"[""q=int(input())\n\nfor e in range(q):\n x,...","{\n ""inputs"": [\n ""3\n2 2 3\n4 3 7\n10 1 9...",interview,https://codeforces.com/problemset/problem/1036/B,
2,2,"You are given three sequences: $a_1, a_2, \ldo...","[""import sys\nimport random\nfrom fractions im...","{\n ""inputs"": [\n ""5\n3\n1 1 1\n2 2 2\n3 3...",interview,https://codeforces.com/problemset/problem/1408/A,
3,3,"You have $n$ barrels lined up in a row, number...","[""def solve():\n n, k = map(int,input().spl...","{\n ""inputs"": [\n ""2\n4 1\n5 5 5 5\n3 2\n0...",interview,https://codeforces.com/problemset/problem/1430/B,
4,4,"You are given a permutation $p=[p_1, p_2, \ldo...","[""for _ in range(int(input())):\n input()\n...","{\n ""inputs"": [\n ""3\n6\n4 5 1 3 2 6\n5\n5...",interview,https://codeforces.com/problemset/problem/1265/B,
5,5,The sequence of $m$ integers is called the per...,"[""def possible(a):\n ans = set()\n s = s...","{\n ""inputs"": [\n ""6\n5\n1 4 3 2 1\n6\n2 4...",interview,https://codeforces.com/problemset/problem/1330/B,
6,6,Arthur owns a ski resort on a mountain. There ...,"[""import sys\ninput = sys.stdin.readline\nfor ...","{\n ""inputs"": [\n ""2\n4 6\n1 2\n1 3\n2 3\n...",interview,https://codeforces.com/problemset/problem/1368/E,
7,7,The only difference between easy and hard vers...,"[""import sys\ndef I():\n return sys.stdin.r...","{\n ""inputs"": [\n ""3\n3\n1 5\n2 10\n2 8\n7...",interview,https://codeforces.com/problemset/problem/1251/E2,
8,8,You like playing chess tournaments online.\n\n...,"[""import sys\ninput = sys.stdin.readline\n\nde...","{\n ""inputs"": [\n ""8\n5 2\nWLWLL\n6 5\nLLL...",interview,https://codeforces.com/problemset/problem/1427/B,
9,9,Alice and Bob play a game. They have a binary ...,"[""for _ in range(int(input())):\n s = input...","{\n ""inputs"": [\n ""5\n01111001\n0000\n1111...",interview,https://codeforces.com/problemset/problem/1398/B,

In [104]:
batch_response = preprocessing(batches[0])

Error generating response for prompt: 0
Invalid operation: The `response.text` quick accessor requires the response to contain a valid `Part`, but none were returned. The candidate's [finish_reason](https://ai.google.dev/api/generate-content#finishreason) is 4. Meaning that the model was reciting from copyrighted material.
1 done
2 done
3 done
4 done
5 done
6 done
Error generating response for prompt: 7
Invalid operation: The `response.text` quick accessor requires the response to contain a valid `Part`, but none were returned. The candidate's [finish_reason](https://ai.google.dev/api/generate-content#finishreason) is 4. Meaning that the model was reciting from copyrighted material.
8 done
9 done

In [102]:
generated_outputs = [
    response.get("generated_output") 
    for response in batch_response
    if "generated_output" in response
]
for i, output in enumerate(generated_outputs):
    print(f"Response {i+1}: {output}")

Response 1:
Response 2: ```python
def solve():
    q = int(input())
    for _ in range(q):
        n, m, k = map(int, input().split())

        max_dist = max(n, m)
        min_dist = min(n, m)

        if (n + m) > k or (k - (n + m)) % 2 != 0 or k < max_dist:
            print(-1)
            continue

        diag = min_dist
        rem_moves = k - (n + m)

        rem_moves //= 2

        diag += rem_moves
        print(diag)


solve()
```
Response 3: ```python
def solve():
    n = int(input())
    a = list(map(int, input().split()))
    b = list(map(int, input().split()))
    c = list(map(int, input().split()))

    p = []
    p.append(a[0])

    for i in range(1, n):
        if a[i] != p[-1]:
            p.append(a[i])
        elif b[i] != p[-1]:
            p.append(b[i])
        else:
            p.append(c[i])

    if p[-1] == p[0]:
        if a[0] != p[-1]:
            p[-1] = a[0]
        elif b[0] != p[-1]:
            p[-1] = b[0]
        else:
            p[-1] = c[0]


    print(*p)


t = int(input())
for _ in range(t):
    solve()

```
Response 4: ```python
def solve():
  n, k = map(int, input().split())
  a = list(map(int, input().split()))

  if sum(a) == 0:
    print(0)
    return

  a.sort(reverse=True)

  ans = sum(a[:k+1])
  print(ans)

t = int(input())
for _ in range(t):
  solve()

```
Response 5:
Response 6: ```python
def solve():
  n = int(input())
  a = list(map(int, input().split()))

  ans = []
  for l1 in range(1, n):
    l2 = n - l1
    p1 = a[:l1]
    p2 = a[l1:]

    if max(p1) > l1 or max(p2) > l2:
      continue

    is_p1_perm = True
    counts1 = {}
    for x in p1:
      counts1[x] = counts1.get(x, 0) + 1
    for i in range(1, l1 + 1):
      if i not in counts1 or counts1[i] != 1:
        is_p1_perm = False
        break

    is_p2_perm = True
    counts2 = {}
    for x in p2:
      counts2[x] = counts2.get(x, 0) + 1
    for i in range(1, l2 + 1):
      if i not in counts2 or counts2[i] != 1:
        is_p2_perm = False
        break

    if is_p1_perm and is_p2_perm:
      ans.append((l1, l2))

  print(len(ans))
  for l1, l2 in ans:
    print(l1, l2)


t = int(input())
for _ in range(t):
  solve()
```
Response 7: ```python
def solve():
    n, m = map(int, input().split())
    edges = []
    for _ in range(m):
        u, v = map(int, input().split())
        edges.append((u, v))

    adj = [[] for _ in range(n + 1)]
    for u, v in edges:
        adj[u].append(v)

    closed = set()

    for i in range(1,n+1):
        if len(adj[i]) >= 2:
            closed.add(i)

    print(len(closed))
    print(*sorted(list(closed)))


T = int(input())
for _ in range(T):
    solve()

```
Response 8:
Response 9: ```python
def solve():
  n, k = map(int, input().split())
  s = input()

  wins = []
  for i in range(n):
    if s[i] == 'W':
      wins.append(i)

  if len(wins) == 0:
    if k >= 1:
      print(1 + 2 * (min(n -1, k) ))
    else:
      print(0)
    return

  gaps = []
  for i in range(len(wins) - 1):
    gaps.append(wins[i+1] - wins[i] - 1)

  gaps.sort()

  score = 1
  for i in range(len(wins) -1):
    if wins[i+1] - wins[i] == 1:
      score += 2
    else:
      score += 1



  for gap in gaps:
    if k == 0:
      break
    if gap <= k:
      k -= gap
      score += 2 * gap
    else:
      score += 2 * k
      k = 0
      break



  if k > 0:

    score += min(k*2, (wins[0] + (n-1-wins[-1]) + k)*2 - k *2 + 1 if wins[0] + (n-1-wins[-1]) > k else (wins[0] + (n-1-wins[-1]) + k)*2  - k)

  print(score)


t = int(input())
for _ in range(t):
  solve()

```
Response 10:

In [87]:
for batch in batches:
    batch_responses = preprocessing(batch)  # Your `preprocessing` function
    responses.extend(batch_responses)

Error generating response for prompt: 0
Invalid operation: The `response.text` quick accessor requires the response to contain a valid `Part`, but none were returned. The candidate's [finish_reason](https://ai.google.dev/api/generate-content#finishreason) is 4. Meaning that the model was reciting from copyrighted material.
1 done
2 done
3 done

KeyboardInterrupt:

### Defining the model

In [ ]:
from transformers import T5ForConditionalGeneration

model = T5ForConditionalGeneration.from_pretrained("Salesforce/codet5-base")
model.resize_token_embeddings(len(tokenizer))  # Resize embeddings if tokenizer changes

In [ ]:
print(model.num_parameters())  # Optional: Check total parameters

### FineTune With Trainer API

### Save and Evaluate the Model